// All the words: every part has a Kid explanation and a Grown-up explanation.

export const PARTS = {
  case: {
    name: 'Case', emoji: '🏠', role: 'The House',
    kid: "The case is the computer's house. It keeps all the parts safe inside, and its fans blow cool air through it like wind through open windows.",
    adult: 'A mid-tower ATX case: a steel frame with a tempered-glass side panel. The motherboard sits on brass standoffs, cables hide behind the motherboard tray, and a shroud covers the power supply. Before buying, check: motherboard size support (ATX / Micro-ATX / Mini-ITX), maximum GPU length, maximum CPU cooler height, and dust filters.',
    facts: ['Hot air rises, so cases usually blow warm air out of the top and back.', 'The little gold posts on the back wall are called standoffs. They stop the motherboard touching the metal and short-circuiting.'],
    specs: { Size: '45 × 46 × 21 cm', 'Fits boards': 'ATX, Micro-ATX, Mini-ITX', Material: 'Steel + tempered glass' },
  },
  motherboard: {
    name: 'Motherboard', emoji: '🏙️', role: 'The City Roads',
    kid: 'The motherboard is like a city full of roads. Every part plugs into it, and tiny copper roads carry messages between the parts super fast.',
    adult: 'The main circuit board (ATX is 305 × 244 mm). It has the CPU socket, the VRM (power delivery for the CPU, under the finned heatsinks), DIMM slots for RAM, PCIe slots for the graphics card, M.2 slots for SSDs, and the chipset (extra USB, SATA and PCIe lanes). The socket and chipset decide which CPUs the board supports. The rear I/O panel has the USB, network and audio ports.',
    facts: ['A motherboard is a sandwich of 6 to 12 thin copper layers glued together.', 'Look closely at the board: you can see groups of wiggly lines leading to the RAM. They are the memory bus.'],
    specs: { 'Form factor': 'ATX (30.5 × 24.4 cm)', Socket: 'LGA (1,700 contact pads)', 'RAM slots': '4 × DDR5', 'Expansion': '2 × PCIe x16, 2 × PCIe x1, M.2' },
  },
  cpu: {
    name: 'CPU (Processor)', emoji: '🧠', role: 'The Brain',
    kid: 'The CPU is the brain! It solves billions of tiny math problems every single second. That is faster than everyone on Earth counting together.',
    adult: 'The Central Processing Unit runs program instructions. Desktop CPUs today have 6 to 24 cores and run at about 4 to 6 GHz, with billions of transistors. The metal lid (IHS, the integrated heat spreader) moves heat from the silicon underneath to the cooler. The gold triangle in one corner marks pin 1: line it up with the triangle on the socket.',
    facts: ['Look inside a CPU (and Apple’s M5) in 🔬 Chip Lab.', 'The first microprocessor (Intel 4004, 1971) had 2,300 transistors. A modern CPU has billions.', 'Never push a CPU into its socket. Lay it in gently and let the lever do the work. Bent pins are the #1 building mistake!'],
    specs: { Cores: '8 cores / 16 threads', Speed: 'up to 4.8 GHz', Size: '4 × 4 cm', Power: '~105 W' },
  },
  paste: {
    name: 'Thermal Paste', emoji: '🧴', role: 'Heat Glue',
    kid: 'Thermal paste is like toothpaste for the CPU! Metal looks smooth, but it has tiny bumps. The paste fills them so heat can jump from the CPU into the cooler.',
    adult: 'Thermal interface material (TIM). Even polished metal has microscopic gaps, and air in those gaps is an insulator. A pea-sized dot in the centre spreads out into a thin layer when the cooler is tightened down. More paste is not better: it just makes a mess.',
    facts: ['Many coolers come with the paste already on them.', 'A pea-sized dot is enough for the whole CPU.'],
    specs: { Amount: 'Pea-sized (~0.3 ml)', Conductivity: '~8 W/m·K' },
  },
  cooler: {
    name: 'CPU Cooler', emoji: '❄️', role: 'The Air Conditioner',
    kid: 'The CPU gets hot, like a stove! The cooler has copper pipes that carry the heat up into lots of thin metal fins, and then the fan blows the heat away.',
    adult: 'A tower air cooler. The copper base sits on the CPU. The sealed heat pipes hold a little liquid: it boils at the hot end, the vapour travels to the fins, turns back into liquid and flows back. This phase change moves heat very well. The fan pushes air through the aluminium fins toward the rear exhaust fan. The alternative is an AIO liquid cooler with a pump and a radiator.',
    facts: ['A heat pipe moves heat many times better than a solid copper bar the same size.', 'Coolers are rated by TDP. This one handles about 220 W.'],
    specs: { Height: '15.5 cm', 'Heat pipes': '4 × 6 mm copper', Fan: '120 mm' },
  },
  ram: {
    name: 'RAM (Memory)', emoji: '📝', role: 'The Desk',
    kid: "RAM is the computer's desk. Whatever you're working on right now sits on the desk so it's quick to grab. When the power turns off, the desk gets wiped clean!",
    adult: 'Random Access Memory (DDR5 DIMMs) is very fast working memory for programs that are running. It is volatile: it forgets everything when the power goes off. With two sticks, use slots A2 and B2 (the 2nd and 4th from the CPU) for dual-channel mode. The notch in the gold contacts is off-centre, so a stick only fits one way, and DDR4 and DDR5 have their notches in different places.',
    facts: ['This is why you save your work! Saving copies it from RAM (the desk) to the SSD (the bookshelf).', 'Press RAM straight down until both clips click. It needs more force than you expect.', 'Want to see inside? Open 🔬 Chip Lab → RAM stick.'],
    specs: { Type: 'DDR5-6000', Capacity: '2 × 16 GB = 32 GB', Channels: 'Dual channel' },
  },
  ssd: {
    name: 'SSD (Storage)', emoji: '🎒', role: 'The Backpack',
    kid: 'The SSD is a backpack that never forgets. Your games, photos and drawings stay safe in it, even when the computer is turned off.',
    adult: 'An M.2 NVMe solid-state drive. "2280" means 22 mm wide and 80 mm long. It stores data in NAND flash chips, and a controller chip manages them. It talks to the CPU over PCIe lanes: a PCIe 4.0 drive reads about 7,000 MB/s, around 50× faster than a hard drive. It has no moving parts.',
    facts: ['This 2 TB SSD is the size of a stick of gum and holds as much as about 1.4 million floppy disks.', 'Slide it in at an angle, press it flat, then add one tiny screw.'],
    specs: { Format: 'M.2 2280 NVMe', Capacity: '2 TB', Speed: '7,000 MB/s read' },
  },
  gpu: {
    name: 'Graphics Card (GPU)', emoji: '🎨', role: 'The Artist',
    kid: 'The graphics card is the artist! It draws every picture you see on the screen. In games it paints more than 60 brand-new pictures every second.',
    adult: 'The Graphics Processing Unit has thousands of small cores working in parallel. It renders 3D graphics and speeds up video and AI work. It has its own fast memory (VRAM, 8 to 24 GB of GDDR6/6X/7). It goes in the top PCIe x16 slot, the one nearest the CPU, and needs its own power cables. Plug the monitor into the graphics card, not into the motherboard!',
    facts: ['A high-end GPU has over 10,000 cores.', 'It is often the biggest and heaviest part in the computer.'],
    specs: { Length: '30 cm', Slot: 'PCIe 4.0 x16', VRAM: '16 GB GDDR6', Power: '2 × 8-pin, ~300 W' },
  },
  psu: {
    name: 'Power Supply (PSU)', emoji: '❤️', role: 'The Heart',
    kid: 'The power supply is the heart. It takes the strong electricity from the wall and turns it into gentle, safe power that every part can use.',
    adult: 'The PSU converts AC mains power (120/230 V) into DC: +12 V for the CPU, GPU and fans, plus +5 V and +3.3 V. It is rated in watts (750 to 850 W is common) and by efficiency (80 PLUS Bronze, Gold or Platinum). A modular PSU lets you attach only the cables you need. Never open a PSU. Its capacitors can hold a dangerous charge even after it is unplugged.',
    facts: ['Mount it fan-down so it breathes cool air through the dust filter under the case.', '"80 PLUS Gold" means at least 87% of the power from the wall reaches your parts.'],
    specs: { Wattage: '850 W', Efficiency: '80 PLUS Gold', Type: 'Fully modular ATX' },
  },
  fans: {
    name: 'Case Fans', emoji: '🌬️', role: 'The Lungs',
    kid: "Fans are the computer's lungs. They breathe cool air in at the front and breathe warm air out at the back.",
    adult: '120 mm fans. Air always blows out of the side with the support arms (the struts). Front fans are intakes; rear and top fans are exhausts. Having slightly more intake than exhaust (positive pressure) keeps dust down, because air leaks out of the gaps instead of being sucked in through them.',
    facts: ['The glowing colours are RGB LEDs. They look cool but do not make it faster (sorry!).', 'A fan spins about 1,500 times a minute.'],
    specs: { Size: '120 mm', Speed: '~1,500 RPM', Airflow: '~60 CFM each' },
  },
  cables: {
    name: 'Power Cables', emoji: '🔌', role: 'The Veins',
    kid: 'Cables are like veins. They carry power from the heart (the PSU) to every part that needs it.',
    adult: 'There are four main cables. The 24-pin ATX powers the motherboard (right edge). The 8-pin EPS powers the CPU (top-left corner). PCIe 8-pin or 12V-2x6 cables power the graphics card. SATA power is for drives. Hide the extra cable behind the motherboard tray so air can flow freely.',
    facts: ['The 24-pin plug is the hardest to push in. Squeeze the clip and push firmly until it clicks.', 'Each connector is shaped so it only fits one way.'],
    specs: { Motherboard: '24-pin ATX', CPU: '8-pin EPS', GPU: '2 × PCIe 8-pin' },
  },
  panel: {
    name: 'Glass Side Panel', emoji: '🪟', role: 'The Window',
    kid: 'A see-through window so you can look at everything you built!',
    adult: 'A tempered-glass side panel. It is strong, but can shatter if its edges hit something hard, so set it down on something soft while you build. It also keeps air flowing the right way through the case.',
    facts: ['Take the glass panel off first and put it somewhere safe before you start building.'],
    specs: { Material: '4 mm tempered glass' },
  },
};

// The real-world build order. kidTask describes the part's *job* so kids must pick the right part.
export const STEPS = [
  { part: 'cpu', title: 'Install the CPU', kidTask: "Put the computer's BRAIN 🧠 into its socket",
    how: 'Lift the lever, open the load plate, match the gold triangle to the socket triangle, lay it in gently, then close the plate and lever. The plastic cover pops off by itself.',
    kidHow: 'Line up the little gold triangles, then lay it in gently. Never push!',
    view: { target: 'socket', offset: [10, 24, 20] } },
  { part: 'ssd', title: 'Install the M.2 SSD', kidTask: 'Add the BACKPACK 🎒 that remembers your games',
    how: 'Slide the SSD into the M.2 slot at about a 20° angle, press it flat, and fix it with the tiny M.2 screw.',
    kidHow: 'Slide it in at a slant, push it flat, and add one tiny screw.',
    view: { target: 'ghost', offset: [8, 22, 18] } },
  { part: 'ram', title: 'Install the RAM', kidTask: 'Add the DESK 📝 where the computer keeps its work',
    how: 'Open the slot clips. Install into A2 and B2 (the 2nd and 4th slots from the CPU) for dual channel. Line up the notch and press firmly until both clips click.',
    kidHow: 'Open the clips, line up the notch, and press down hard until you hear CLICK!',
    view: { target: 'ghost', offset: [12, 24, 18] } },
  { part: 'paste', title: 'Apply thermal paste', kidTask: 'Put the "TOOTHPASTE" 🧴 on the brain',
    how: 'Put a pea-sized dot in the centre of the CPU lid. The cooler will spread it out.',
    kidHow: 'Just a tiny pea-sized dot in the middle!',
    view: { target: 'socket', offset: [8, 18, 16] } },
  { part: 'cooler', title: 'Mount the CPU cooler', kidTask: 'Add the AIR CONDITIONER ❄️ that keeps the brain cool',
    how: "Place the cooler straight down on the CPU and tighten the screws a little at a time in an X pattern so it presses down evenly. Plug its fan into the CPU_FAN header.",
    kidHow: 'Set it gently on top of the brain, then screw it down a little at a time.',
    view: { target: 'socket', offset: [26, 30, 38] } },
  { part: 'psu', title: 'Install the power supply', kidTask: 'Put the HEART ❤️ into the house',
    how: 'Slide the PSU into the bottom of the case, fan facing down, and screw it in from the back.',
    kidHow: 'The heart goes at the bottom, with its fan looking down at the floor.',
    view: { target: 'case', offset: [30, 12, 55], focusY: 8 } },
  { part: 'motherboard', title: 'Mount the motherboard', kidTask: 'Move the CITY 🏙️ (with the brain, desk and backpack) into the house',
    how: 'Line up the rear I/O with the case opening and the mounting holes with the standoffs, then drive in all 9 screws. Do not overtighten them.',
    kidHow: 'Lower it onto the gold posts and screw it down.',
    view: { target: 'case', offset: [35, 20, 70], focusY: 26 } },
  { part: 'gpu', title: 'Install the graphics card', kidTask: 'Plug in the ARTIST 🎨 who draws the pictures',
    how: 'Remove the slot covers, press the card firmly into the top PCIe x16 slot until the latch clicks, then screw the bracket to the case.',
    kidHow: 'Push it into the long slot near the top until it clicks.',
    view: { target: 'case', offset: [25, 5, 60], focusY: 24 } },
  { part: 'cables', title: 'Connect power cables', kidTask: 'Connect the VEINS 🔌 so power can flow',
    how: 'Connect the 24-pin to the motherboard, the 8-pin EPS to the CPU header (top-left) and the PCIe cables to the GPU. Route the extra length behind the tray.',
    kidHow: 'Plug each cable into the socket that has the same shape.',
    view: { target: 'case', offset: [20, 10, 65], focusY: 28 } },
  { part: 'panel', title: 'Close the side panel', kidTask: 'Put the WINDOW 🪟 back on',
    how: 'Put the tempered glass back on and tighten the thumb screws by hand.',
    kidHow: 'Put the window back on so you can see inside.',
    view: { target: 'case', offset: [30, 15, 80], focusY: 23 } },
  { part: 'power', title: 'Power on!', kidTask: 'Press the POWER button ⏻!',
    how: 'Switch the PSU on at the back, then press the power button. If the fans spin and the screen shows the BIOS, it works!',
    kidHow: 'Press the glowing button on top of the case!',
    view: { target: 'power', offset: [18, 22, 36] } },
];

// Order the parts appear in the build tray (deliberately not the build order).
export const TRAY = ['motherboard', 'gpu', 'cpu', 'ram', 'psu', 'ssd', 'cooler', 'paste', 'cables', 'panel', 'power'];

export const FIND = [
  { part: 'cpu', kid: 'Find the computer’s BRAIN 🧠', adult: 'Click the component that executes program instructions.' },
  { part: 'gpu', kid: 'Find the ARTIST that draws pictures 🎨', adult: 'Click the component that renders frames for the display.' },
  { part: 'psu', kid: 'Find the HEART that gives power ❤️', adult: 'Click the component that converts AC to 12 V DC.' },
  { part: 'ram', kid: 'Find the DESK where it keeps its work 📝', adult: 'Click the volatile working memory.' },
  { part: 'ssd', kid: 'Find the BACKPACK that remembers your games 🎒', adult: 'Click the non-volatile NVMe storage.' },
  { part: 'fans', kid: 'Find the LUNGS that breathe air 🌬️', adult: 'Click the intake/exhaust fans.' },
  { part: 'motherboard', kid: 'Find the CITY where everything plugs in 🏙️', adult: 'Click the main circuit board.' },
  { part: 'cooler', kid: 'Find the AIR CONDITIONER for the brain ❄️', adult: 'Click the heat-pipe tower cooler.' },
  { part: 'cables', kid: 'Find the VEINS that carry power 🔌', adult: 'Click the 24-pin ATX / EPS / PCIe power cables.' },
];

export const EXHIBITS = {
  punchcard: {
    name: 'Punched Card', year: '1890 – 1970s', emoji: '🗂️', play: 'Hold it up to the light',
    stats: [['Holds', '80 characters'], ['Made of', 'Stiff paper']],
    kid: 'Before screens and keyboards, people told computers what to do by punching holes in paper cards! Every hole pattern is a letter or number. This card secretly says a message. Can you guess it?',
    adult: 'Herman Hollerith used punched cards to count the 1890 US census. The IBM 80-column card (1928) became the standard. Each column holds one character: a digit is one punch in rows 0–9, and a letter is a "zone" punch (row 12, 11 or 0) plus a digit punch. Programs were stacks of thousands of cards, and dropping the deck was a disaster. This card is really punched with "HELLO FUTURE PC BUILDERS" in Hollerith code.',
    fact: 'One phone photo (3 MB) would need about 37,500 cards, a stack almost 7 metres tall!',
  },
  tube: {
    name: 'Vacuum Tube', year: '1904 – 1950s', emoji: '💡', play: 'Switch it on',
    stats: [['Job', 'An on/off switch'], ['ENIAC used', '17,468']],
    kid: 'This glass bottle is a switch that works like a light bulb. The first big computer, ENIAC, used 17,468 of them! It filled a whole room and weighed as much as 5 elephants.',
    adult: 'A vacuum tube controls electrons flowing through a vacuum, from a heated cathode to a plate, using a grid. That lets it work as an amplifier or a switch. ENIAC (1945) used 17,468 tubes, weighed about 27 tonnes and drew 150 kW. Tubes ran hot and burned out often, so engineers spent a lot of time finding and replacing dead ones.',
    fact: 'Bugs! In 1947 engineers found a real moth stuck in the Harvard Mark II computer and taped it into their logbook as the "first actual case of bug being found".',
  },
  transistor: {
    name: 'Transistor', year: '1947', emoji: '🔀', play: 'Flip the switch',
    stats: [['Job', 'A tiny switch'], ['In your phone', '10+ billion']],
    kid: 'The transistor does the same job as the glass tube, but it is tiny, cool and almost never breaks. Every computer today is made of billions of them.',
    adult: 'Bardeen, Brattain and Shockley invented the transistor at Bell Labs in 1947 and won the 1956 Nobel Prize in Physics for it. It is a semiconductor switch: a small current or voltage at one terminal controls a bigger current between the other two. Shown here is a common single transistor in a TO-92 package (a 2N3904). Inside a CPU, transistors are only a few nanometres across.',
    fact: 'Modern chips pack in more than 100 million transistors per square millimetre.',
  },
  hdd: {
    name: 'Hard Disk Drive', year: '1956 → today', emoji: '💿', play: 'Spin it up',
    stats: [['1956 (IBM 350)', '3.75 MB, ~1 tonne'], ['Today', 'up to 30 TB']],
    kid: 'A hard drive is like a super-fast record player. A shiny disk spins really fast, and a tiny arm reads and writes using magnets. The first one was as big as two fridges!',
    adult: 'The IBM 350 RAMAC (1956) stored 3.75 MB on fifty 24-inch platters and weighed about a tonne. A modern 3.5" drive spins its platters at 7,200 RPM. The read/write head floats just a few nanometres above the surface on a cushion of air. HDDs are still the cheapest way to store huge amounts of data, but SSDs are much faster.',
    fact: 'The head flies so low that a fingerprint on the platter would be like a mountain to it.',
  },
  i4004: {
    name: 'Intel 4004', year: '1971', emoji: '🔲', play: 'Flip it over',
    stats: [['Transistors', '2,300'], ['Speed', '740 kHz']],
    kid: 'This is the first "computer brain on a chip"! It was made for a calculator. Today\'s brains are millions of times more powerful.',
    adult: 'The 4004 was the first commercially available microprocessor: a whole 4-bit CPU on one chip. It had 2,300 transistors on a 10 µm process and ran at 740 kHz. Intel designed it for the Busicom 141-PF calculator. Federico Faggin, Ted Hoff, Stanley Mazor and Masatoshi Shima designed it. It came in a 16-pin ceramic DIP package.',
    fact: 'A modern CPU has about 5 million times more transistors.',
  },
  floppy8: {
    name: '8-inch Floppy Disk', year: '1971', emoji: '💾', play: 'Spin the disk',
    stats: [['Holds', '80 KB – 1.2 MB'], ['Size', '20 cm square']],
    kid: 'The very first floppy disk! It was as big as a dinner plate and bendy, which is why it was called "floppy".',
    adult: 'IBM introduced the 8" floppy (the 23FD) in 1971 to load microcode into its mainframes. The first version was read-only and held 80 KB. Later double-sided, double-density disks held about 1.2 MB. The magnetic disc spins inside a protective jacket, and the drive head reads it through the oval slot.',
    fact: 'The US nuclear forces used 8-inch floppies until 2019!',
  },
  floppy525: {
    name: '5¼-inch Floppy Disk', year: '1976', emoji: '💾', play: 'Spin the disk',
    stats: [['Holds', '160 KB – 1.2 MB'], ['Size', '13.3 cm square']],
    kid: 'A smaller floppy disk that kids in the 1980s used to play games! You had to be careful not to bend it or touch the brown disk inside.',
    adult: 'Shugart Associates launched the 5¼" format in 1976. The IBM PC used 160–360 KB disks, and high-density disks later held 1.2 MB. To write-protect a disk you covered the notch on its side with a sticky tab. People cut a second notch to use the back side too, and called them "flippy" disks.',
    fact: 'Some big games came on 10 or more floppy disks, and you had to swap them while you played.',
  },
  ibmpc: {
    name: 'IBM Personal Computer', year: '1981', emoji: '🖥️', play: 'Type a command',
    stats: [['CPU', 'Intel 8088 @ 4.77 MHz'], ['RAM', '16 KB – 256 KB']],
    kid: 'One of the first computers people put at home and in offices. It had no mouse and no pictures. You typed words to tell it what to do, and the screen glowed green!',
    adult: 'The IBM PC 5150 (August 1981) used an Intel 8088 CPU at 4.77 MHz, came with 16–256 KB of RAM, and had one or two 5¼" floppy drives. It ran PC DOS. IBM built it from off-the-shelf parts and published how it worked, so other companies made "IBM compatible" clones. That is why most computers today are called PCs.',
    fact: 'Your phone is well over 100,000 times faster than this computer.',
  },
  floppy35: {
    name: '3½-inch Floppy Disk', year: '1982', emoji: '💾', play: 'Open the shutter',
    stats: [['Holds', '1.44 MB'], ['Size', '9 × 9.4 cm']],
    kid: 'This is the famous one! It has a hard plastic shell and a metal door that slides open. The "Save" button in lots of apps still looks like this disk!',
    adult: 'Sony introduced the 3½" disk in 1982, and the 1.44 MB high-density version became the standard from 1987. The metal shutter slides open inside the drive to show the magnetic disc. The small sliding tab is the write-protect switch, and the hole in the other corner marks it as high density. Microsoft shipped Windows 95 on 13 of these disks.',
    fact: 'The 💾 save icon is a picture of this disk. Lots of people who click it every day have never seen a real one!',
  },
  cd: {
    name: 'CD-ROM', year: '1985', emoji: '📀', play: 'Spin it',
    stats: [['Holds', '650 – 700 MB'], ['= floppies', '~480']],
    kid: 'A shiny disc that is read with a laser beam! The rainbow colours come from millions of tiny bumps on it. One CD holds as much as a stack of about 480 floppy disks.',
    adult: 'Sony and Philips created the Compact Disc in 1982, and CD-ROM followed for data in 1985. A 780 nm laser reads tiny "pits" and "lands" pressed into a spiral track about 5.4 km long. It holds 650 to 700 MB (74 to 80 minutes of audio). The rainbow effect happens because the tracks are so close together (1.6 µm apart) that they split light like a prism.',
    fact: 'If you unrolled the spiral track on a CD, it would be over 5 km long!',
  },
  usb: {
    name: 'USB Flash Drive', year: '2000', emoji: '🔑', play: 'Plug it in',
    stats: [['First (2000)', '8 MB'], ['Today', 'up to 2 TB']],
    kid: 'A tiny memory stick for your pocket. There\'s nothing spinning inside, just a chip that remembers everything!',
    adult: 'The first USB flash drives appeared in 2000 (IBM\'s DiskOnKey, made by M-Systems, and Trek\'s ThumbDrive) and held 8 MB. They use the same NAND flash memory as SSDs. They quickly replaced floppy disks because they were smaller, sturdier and held far more.',
    fact: 'An 8 MB flash drive held as much as about 5 floppy disks, and it fit on a keychain.',
  },
  nvme: {
    name: 'M.2 NVMe SSD', year: '2013 → today', emoji: '⚡', play: 'Spin it',
    stats: [['Holds', 'up to 8 TB'], ['Speed', '7,000–14,000 MB/s']],
    kid: 'Today\'s storage is a thin stick of chips that is SO fast. It can load a whole movie in less than a second!',
    adult: 'NVMe drives connect straight to PCIe lanes. Compared with the older SATA interface, that means much lower delay and much more bandwidth. PCIe 5.0 drives can read about 14 GB/s. It is the same kind of drive you install in the Build mode.',
    fact: 'The 1956 hard drive weighed about a tonne and held 3.75 MB. A 2 TB one weighs about 7 grams and holds over 500,000 times more.',
  },
};
export const EXHIBIT_ORDER = ['punchcard', 'tube', 'transistor', 'hdd', 'i4004', 'floppy8', 'floppy525', 'ibmpc', 'floppy35', 'cd', 'usb', 'nvme'];

// "How many floppies?" calculator (1.44 MB disk = 1,474,560 bytes, 3.3 mm thick)
export const FLOPPY_ITEMS = [
  { name: 'A phone photo', emoji: '📷', bytes: 4e6 },
  { name: 'A song', emoji: '🎵', bytes: 5e6 },
  { name: 'A 2-hour HD movie', emoji: '🎬', bytes: 4e9 },
  { name: 'A big video game', emoji: '🎮', bytes: 100e9 },
  { name: 'A 2 TB SSD', emoji: '⚡', bytes: 2e12 },
];
export const HEIGHTS = [
  { name: 'a kid', emoji: '🧒', m: 1.3 },
  { name: 'a giraffe', emoji: '🦒', m: 5.5 },
  { name: 'a house', emoji: '🏠', m: 10 },
  { name: 'the Statue of Liberty', emoji: '🗽', m: 93 },
  { name: 'the Eiffel Tower', emoji: '🗼', m: 330 },
  { name: 'the Burj Khalifa', emoji: '🏙️', m: 828 },
  { name: 'Mount Everest', emoji: '🏔️', m: 8849 },
];

// ---------- Chip Lab ----------
// Floorplans are simplified: block positions follow the real designs' general arrangement, sizes are approximate.
// Coordinates: package-space units (≈ mm); each die's blocks use die-local x (right) / z (down) from its top-left corner.
const B = (id, name, x, z, w, d, color, pattern, extra = {}) => ({ id, name, x, z, w, d, color, pattern, ...extra });

export const CHIPS = {
  m5: {
    name: 'Apple M5', emoji: '🍎', year: '2025', tagline: 'A whole computer on one chip',
    note: 'Simplified layout: Apple doesn’t publish the exact floorplan.',
    stats: [['Made with', '3 nm transistors'], ['CPU', '10 cores (4 P + 6 E)'], ['GPU', '10 cores'], ['Memory speed', '153 GB/s']],
    kid: 'Apple’s M5 is a “system on a chip”. The brain, the artist, the AI helper and the video player all live together on ONE piece of silicon, and they share the same memory right next door.',
    adult: 'The M5 is an SoC (system on a chip) built on third-generation 3 nm technology. It combines a 10-core CPU (4 performance + 6 efficiency cores), a 10-core GPU with a Neural Accelerator in every GPU core, a 16-core Neural Engine, media engines, and a unified memory system (up to 32 GB of LPDDR5X at 153 GB/s) that the CPU, GPU and Neural Engine all read directly, with no copying between them.',
    package: { w: 26, d: 30, color: '#1f4d36' },
    lid: { x: -8.4, z: -12.4, w: 16.8, d: 14.8, label: 'M5', sub: 'Apple silicon' },
    sources: [[-4, 9], [4, 9]],
    dies: [
      { x: -8, z: -12, w: 16, d: 14, blocks: [
        B('pcore', 'P-cores', 0, 0, 6, 4.2, '#e0584f', 'cores', { grid: [2, 2] }),
        B('ecore', 'E-cores', 6, 0, 4.5, 4.2, '#f39a3d', 'cores', { grid: [3, 2] }),
        B('npu', 'Neural Engine', 10.5, 0, 5.5, 4.2, '#b064e6', 'cores', { grid: [4, 4] }),
        B('gpu', 'GPU · 10 cores', 0, 4.2, 9, 6, '#3f8fe8', 'cores', { grid: [5, 2], accel: true }),
        B('slc', 'System cache', 9, 4.2, 7, 3, '#39b58a', 'cache'),
        B('media', 'Media Engine', 9, 7.2, 3.5, 3, '#f2c230', 'logic', { demo: 'media' }),
        B('display', 'Display', 12.5, 7.2, 3.5, 1.5, '#59c7d8', 'logic'),
        B('secure', 'Secure Enclave', 12.5, 8.7, 3.5, 1.5, '#8c96a8', 'logic'),
        B('tb', 'Thunderbolt / USB', 0, 10.2, 6, 2, '#6d7fa3', 'io'),
        B('isp', 'Camera ISP', 6, 10.2, 5, 2, '#d97ab5', 'logic'),
        B('ssdc', 'SSD controller', 11, 10.2, 5, 2, '#7aa36d', 'logic'),
        B('memctl', 'Memory controllers', 0, 12.2, 16, 1.8, '#4c5a78', 'mem'),
      ] },
      { x: -8, z: 3.5, w: 7.6, d: 9, slab: false, blocks: [B('umem', 'Unified memory', 0, 0, 7.6, 9, '#15161a', 'chip', { h: 1.1, label: 'LPDDR5X' })] },
      { x: 0.4, z: 3.5, w: 7.6, d: 9, slab: false, blocks: [B('umem', 'Unified memory', 0, 0, 7.6, 9, '#15161a', 'chip', { h: 1.1, label: 'LPDDR5X' })] },
    ],
    info: {
      pcore: { kid: 'The 4 strongest brain parts. They do the hardest thinking really fast, like when a game starts.', adult: '4 high-performance CPU cores (Apple calls them its fastest ever) with a shared L2 cache. Wide out-of-order designs that run heavy, single-threaded work.' },
      ecore: { kid: '6 helper brains that use very little energy. They do small jobs, so the battery lasts longer.', adult: '6 efficiency cores that handle background and light tasks at a fraction of the power. The OS scheduler decides which core type each thread runs on.' },
      npu: { kid: 'A special brain just for AI, like recognising faces in photos or understanding your voice.', adult: 'A 16-core Neural Engine, a dedicated accelerator for the matrix maths in machine-learning models (on-device dictation, photo search and so on). It does this at far lower power than the CPU or GPU would.' },
      gpu: { kid: 'The artist! 10 drawing cores, and each one now has its own little AI helper too.', adult: 'A 10-core GPU with a Neural Accelerator in every core (Apple quotes over 4× the peak AI compute of M4), a third-generation ray-tracing engine, and second-generation dynamic caching.' },
      slc: { kid: 'A super-fast pocket where the chip keeps things it’s about to need, so it doesn’t have to walk all the way to memory.', adult: 'The System Level Cache (SLC) is shared by the CPU, GPU and other blocks. It cuts trips to DRAM, which saves both time and power.' },
      media: { kid: 'A tiny video machine. It plays and records videos using hardly any energy, so the rest of the chip can rest.', adult: 'Fixed-function hardware for video: H.264, HEVC, ProRes and ProRes RAW encode/decode, plus AV1 decode. Dedicated circuits do these fixed maths steps many times more efficiently than general-purpose cores, which is why a laptop can play video for many hours.' },
      display: { kid: 'Sends the finished pictures to the screen, many times every second.', adult: 'Display engines scan finished frames out to the internal panel and external displays, handling scaling, colour and refresh timing.' },
      secure: { kid: 'A locked safe inside the chip that keeps your fingerprint and passwords secret.', adult: 'The Secure Enclave is an isolated subsystem with its own processor and encrypted memory. It holds Touch ID / Face ID data and encryption keys, and even the main OS can’t read them.' },
      tb: { kid: 'The doors to the outside world, where cables plug in.', adult: 'Thunderbolt / USB 4 controllers for high-speed external ports: displays, storage and docks.' },
      isp: { kid: 'Makes camera pictures look nice: brighter, sharper and less blurry.', adult: 'The image signal processor turns raw camera-sensor data into a clean image (demosaicing, noise reduction, tone mapping) in real time.' },
      ssdc: { kid: 'The librarian for the storage. It knows where every file is kept.', adult: 'Apple puts the SSD controller inside the SoC, so the separate NAND chips on the board act as the drive. It handles wear levelling, error correction and encryption.' },
      memctl: { kid: 'The loading dock where data comes in from the memory chips next door.', adult: 'LPDDR5X memory controllers. With unified memory, every block reads the same pool directly, so data doesn’t have to be copied between CPU and GPU memory. That is what gives 153 GB/s.' },
      umem: { title: 'Unified memory', kid: 'Unified memory: ONE shared desk that the brain, the artist and the AI helper all use together.', adult: 'LPDDR5X DRAM packages sit on the same package as the SoC, very close to it. Short wires mean high bandwidth at low power. The trade-off is that you can’t upgrade it later.' },
    },
  },

  desktop: {
    name: 'Desktop CPU', emoji: '🧩', year: '2022', tagline: 'Built from “chiplets”, like LEGO bricks',
    note: 'Layout in the style of AMD Ryzen 9 7950X (2 core chiplets + 1 I/O die). Sizes are approximate.',
    stats: [['Cores', '16 (2 × 8)'], ['L3 cache', '64 MB'], ['Made with', '5 nm + 6 nm'], ['Memory', 'DDR5, 2 channels']],
    kid: 'Instead of one big chip, this processor is made of three smaller chips working as a team, like LEGO bricks! Two bricks do the thinking, and one brick talks to everything else.',
    adult: 'A chiplet design: two CCDs (core complex dies, 8 cores + 32 MB L3 each, on 5 nm) and one I/O die (6 nm) with the DDR5 memory controller, PCIe 5.0, USB, a small iGPU and a video engine. Small dies are cheaper to make, and the I/O parts don’t need the most expensive process. This package sits under the metal lid you install in Build mode.',
    package: { w: 40, d: 40, color: '#1d5236' },
    lid: { x: -17, z: -17, w: 34, d: 34, label: '16-CORE', sub: 'DESKTOP PROCESSOR' },
    sources: [[22, -6], [22, 6]],
    dies: [
      { x: -14, z: -13, w: 10.6, d: 6.8, blocks: [
        B('cores', 'Cores 1–4', 0, 0, 10.6, 2.6, '#e0584f', 'cores', { grid: [4, 1] }),
        B('l3', 'L3 cache 32 MB', 0, 2.6, 10.6, 1.6, '#39b58a', 'cache'),
        B('cores', 'Cores 5–8', 0, 4.2, 10.6, 2.6, '#e0584f', 'cores', { grid: [4, 1] }),
      ] },
      { x: -14, z: 6, w: 10.6, d: 6.8, blocks: [
        B('cores', 'Cores 9–12', 0, 0, 10.6, 2.6, '#e0584f', 'cores', { grid: [4, 1] }),
        B('l3', 'L3 cache 32 MB', 0, 2.6, 10.6, 1.6, '#39b58a', 'cache'),
        B('cores', 'Cores 13–16', 0, 4.2, 10.6, 2.6, '#e0584f', 'cores', { grid: [4, 1] }),
      ] },
      { x: 2, z: -5, w: 12.4, d: 9.9, blocks: [
        B('ddr', 'DDR5 memory controller', 0, 0, 12.4, 1.8, '#4c5a78', 'mem'),
        B('igpu', 'Mini GPU', 0, 1.8, 5, 4, '#3f8fe8', 'cores', { grid: [2, 1] }),
        B('media', 'Video engine', 5, 1.8, 3, 2, '#f2c230', 'logic', { demo: 'media' }),
        B('display', 'Display', 8, 1.8, 4.4, 2, '#59c7d8', 'logic'),
        B('usb', 'USB', 5, 3.8, 7.4, 2, '#6d7fa3', 'io'),
        B('fabric', 'Infinity Fabric', 0, 5.8, 12.4, 2.3, '#8c96a8', 'logic'),
        B('pcie', 'PCIe 5.0', 0, 8.1, 12.4, 1.8, '#7aa36d', 'io'),
      ] },
    ],
    info: {
      cores: { title: 'CPU cores (16)', kid: 'Each little square is one brain core. This chip has 16! They can all work on different jobs at the same time.', adult: 'Zen-style CPU cores, each with its own L1 and 1 MB L2 cache. With SMT, each core runs 2 threads, so 16 cores give 32 threads.' },
      l3: { title: 'L3 cache', kid: 'A shared pocket for the 8 cores next to it, so they can grab things quickly.', adult: '32 MB of L3 cache per chiplet (64 MB in total), shared by the 8 cores on that die. Fetching from here takes around 10 ns, compared with around 70+ ns from DRAM.' },
      ddr: { kid: 'The door to the RAM sticks. Data from the “desk” comes in here.', adult: 'A dual-channel DDR5 memory controller (each DIMM has 2 × 32-bit subchannels). It connects to the DIMM slots through the motherboard’s memory bus, the wiggly traces you saw in Explore.' },
      igpu: { kid: 'A tiny artist so the computer can show a picture even without a graphics card.', adult: 'A small integrated GPU (2 compute units). It’s enough for the desktop and video, and it’s handy for troubleshooting when there’s no graphics card.' },
      media: { kid: 'A tiny video machine that plays and records videos using hardly any energy.', adult: 'A hardware video block (AMD VCN) for encoding and decoding H.264 and HEVC, plus AV1 decode. It is fixed-function, so it uses far less power than doing the same work on the CPU cores.' },
      display: { kid: 'Sends pictures out through the motherboard’s HDMI port.', adult: 'Display controllers for the motherboard’s video outputs, used when the iGPU is active.' },
      usb: { kid: 'Where the USB ports connect to the chip.', adult: 'USB controllers built into the CPU, with more provided by the motherboard chipset.' },
      fabric: { kid: 'The bridges that connect the three chips so they can talk.', adult: 'Infinity Fabric links join the I/O die to each CCD across the package substrate. Crossing between chiplets adds a little delay compared with staying on one die.' },
      pcie: { kid: 'The road to the graphics card and the SSD.', adult: 'PCIe 5.0 lanes: x16 for the graphics card slot, x4 for an M.2 SSD, and x4 to the chipset.' },
    },
  },

  gpu: {
    name: 'Graphics chip', emoji: '🎨', year: '2022', tagline: 'Thousands of tiny artists at once',
    note: 'Layout in the style of NVIDIA’s AD102 (RTX 4090 class): 12 processing clusters, 144 SMs on the full die. Simplified.',
    stats: [['Shader cores', '16,384 (RTX 4090)'], ['Transistors', '76 billion'], ['Die size', '609 mm²'], ['Memory', '12 × GDDR6X chips']],
    kid: 'A graphics chip is like a huge art class. Instead of a few really smart brains, it has THOUSANDS of simpler ones that each colour in a tiny bit of the picture at the same time.',
    adult: 'A big GPU die splits work across GPCs (graphics processing clusters), each containing SMs (streaming multiprocessors) that hold the CUDA cores, tensor cores and RT cores. A large L2 cache sits in the middle, and a 384-bit memory bus feeds 12 GDDR6X chips on the card. Dedicated media engines (NVENC encoders and an NVDEC decoder) handle video.',
    package: { w: 42, d: 42, color: '#1c4c34' },
    lid: null,
    sources: [[-30, -13], [-30, 13], [30, -13], [30, 13], [-13, -30], [13, -30], [-13, 30], [13, 30]],
    dies: [
      { x: -12.3, z: -12.35, w: 24.6, d: 24.7, blocks: [
        B('mc', 'Memory controllers', 0, 0, 24.6, 1.5, '#4c5a78', 'mem'),
        ...Array.from({ length: 12 }, (_, i) => B('gpc', `GPC ${i + 1}`, i < 6 ? 0 : 15.6, 1.5 + (i % 6) * 3.62, 9, 3.62, '#3f8fe8', 'cores', { grid: [6, 2] })),
        B('l2', 'L2 cache', 9, 1.5, 6.6, 12, '#39b58a', 'cache'),
        B('cmd', 'Command & scheduling', 9, 13.5, 6.6, 2.5, '#8c96a8', 'logic'),
        B('media', 'Media engines', 9, 16, 6.6, 3.5, '#f2c230', 'logic', { demo: 'media' }),
        B('display', 'Display', 9, 19.5, 6.6, 1.8, '#59c7d8', 'logic'),
        B('pcie', 'PCIe interface', 9, 21.3, 6.6, 1.9, '#7aa36d', 'io'),
        B('mc', 'Memory controllers', 0, 23.2, 24.6, 1.5, '#4c5a78', 'mem'),
      ] },
      ...[[-36, -19], [-36, -6], [-36, 7], [24, -19], [24, -6], [24, 7], [-19, -36], [-6, -36], [7, -36], [-19, 24], [-6, 24], [7, 24]].map(([x, z]) => (
        { x, z, w: 12, d: 12, slab: false, blocks: [B('vram', 'Video memory', 0, 0, 12, 12, '#15161a', 'chip', { h: 1.2, label: 'GDDR6X' })] })),
    ],
    info: {
      gpc: { title: 'Processing clusters (GPCs)', kid: 'Each blue block is a team of little artists. 12 teams × 12 groups × 128 painters = over 16,000 painters!', adult: 'Graphics Processing Cluster: 6 TPCs = 12 SMs each (144 SMs on the full die). Each SM has 128 CUDA cores, 4 tensor cores (for AI) and 1 RT core (for ray tracing).' },
      l2: { kid: 'A big shared pocket in the middle so all the teams can share things quickly.', adult: 'The L2 cache (up to 96 MB on the full die, 72 MB on the RTX 4090). A large L2 cuts traffic to GDDR memory, which helps at high resolutions and with ray tracing.' },
      cmd: { kid: 'The teacher who hands out jobs to all the art teams.', adult: 'The front end: the command processor, GigaThread scheduler and geometry work distribution. It turns the driver’s command stream into work spread across the GPCs.' },
      media: { kid: 'The video machines. They let streamers record games without slowing the game down.', adult: 'NVENC encoders (2 on the RTX 4090, with AV1 support) and an NVDEC decoder. They are fixed-function, so recording or streaming barely touches the shader cores.' },
      display: { kid: 'Sends the finished picture out through the HDMI and DisplayPort sockets.', adult: 'The display engine drives DisplayPort / HDMI outputs, including high-refresh and HDR modes.' },
      pcie: { kid: 'The road back to the CPU through the motherboard slot.', adult: 'A PCIe 4.0 x16 host interface: about 32 GB/s each way to the CPU.' },
      mc: { title: 'Memory controllers', kid: 'The loading docks for the video memory chips all around.', adult: '12 × 32-bit GDDR6X controllers = a 384-bit bus, about 1 TB/s of memory bandwidth. That is roughly 10× a desktop CPU’s dual-channel DDR5.' },
      vram: { title: 'Video memory (GDDR6X)', kid: 'The artist’s own paint shelf: very fast memory just for pictures.', adult: 'GDDR6X chips (2 GB each, 24 GB in total). They use PAM4 signalling at ~21 Gbps per pin.' },
    },
  },

  dimm: {
    name: 'RAM stick (DDR5)', emoji: '📝', year: '2021', tagline: 'What’s under the heat spreader',
    note: 'A 16 GB single-rank DDR5 DIMM, shown at ⅓ scale (the real stick is 133 mm long).',
    stats: [['Pins', '288'], ['Chips', '8 × 2 GB'], ['Channels', '2 × 32-bit per stick'], ['Voltage', '1.1 V (PMIC on stick)']],
    kid: 'Take the metal cover off a RAM stick and you find a row of black memory chips. Each one holds 2 GB, and together they make this 16 GB “desk”.',
    adult: 'A DDR5 UDIMM. Unlike DDR4, each stick is split into two independent 32-bit subchannels (A and B) for better efficiency, and voltage regulation moved onto the module itself (the PMIC). The SPD hub stores the timings and XMP/EXPO profiles your BIOS reads, and it includes a temperature sensor.',
    package: { w: 44.45, d: 10.4, color: '#1f5b3a', t: 0.45 },
    lid: { x: -22.2, z: -5.2, w: 44.4, d: 9.2, h: 0.5, label: 'VELOCITY DDR5', sub: '6000 MT/s · 16 GB', color: '#3b3f46' },
    sources: [[0, 5.6], [-10, 5.6], [10, 5.6]],
    dies: [
      ...[0, 1, 2, 3, 4, 5, 6, 7].map(i => ({ x: -20.5 + i * 5.1 + (i > 3 ? 1.2 : 0), z: -4, w: 3.6, d: 3.3, slab: false,
        blocks: [B('dram', i < 4 ? 'Subchannel A' : 'Subchannel B', 0, 0, 3.6, 3.3, '#15161a', 'chip', { h: 0.4, label: '2 GB', tint: i < 4 ? '#e0584f' : '#3f8fe8' })] })),
      { x: -1.2, z: 0.4, w: 2.4, d: 1.6, slab: false, blocks: [B('pmic', 'PMIC', 0, 0, 2.4, 1.6, '#15161a', 'chip', { h: 0.35, label: 'PMIC' })] },
      { x: 17, z: 0.4, w: 1.6, d: 1.2, slab: false, blocks: [B('spd', 'SPD hub', 0, 0, 1.6, 1.2, '#15161a', 'chip', { h: 0.3, label: 'SPD' })] },
      { x: -22.2, z: 4, w: 21.2, d: 1.2, slab: false, blocks: [B('pins', 'Gold contacts', 0, 0, 21.2, 1.2, '#d6a73c', 'gold', { h: 0.05 })] },
      { x: -0.4, z: 4, w: 0.8, d: 1.2, slab: false, blocks: [B('notch', 'Key notch', 0, 0, 0.8, 1.2, '#0c0f16', 'logic', { h: 0.05, label: ' ' })] },
      { x: 1, z: 4, w: 21.2, d: 1.2, slab: false, blocks: [B('pins', 'Gold contacts', 0, 0, 21.2, 1.2, '#d6a73c', 'gold', { h: 0.05 })] },
    ],
    info: {
      dram: { title: 'DRAM chips', kid: 'The memory chips! Each black square holds 2 GB. The red ones and the blue ones work as two separate teams so they can do two jobs at once.', adult: 'Eight 16 Gb (2 GB) x8 DRAM chips. The four on the left form 32-bit subchannel A and the four on the right form subchannel B. Each subchannel takes its own commands, which keeps more of the memory busy. Open “Inside a memory chip” to look inside one.' },
      pmic: { kid: 'A little power helper that gives the memory chips exactly the right amount of electricity.', adult: 'Power Management IC. DDR5 moved voltage regulation from the motherboard onto the DIMM, turning 5 V into the ~1.1 V the DRAM needs, right next to the chips. That makes the voltage cleaner.' },
      spd: { kid: 'A tiny name tag that tells the computer how fast this RAM can go.', adult: 'The SPD hub (Serial Presence Detect) is an EEPROM holding the JEDEC timings and XMP/EXPO overclocking profiles, plus a temperature sensor. The BIOS reads it at boot. That is how “enable XMP” knows what to set.' },
      pins: { title: 'Gold contacts', kid: 'The gold fingers that touch the motherboard slot. Gold doesn’t rust, so the connection stays good.', adult: '288 contacts (144 per side) carrying data, address/command, clocks and power. They are gold-plated for corrosion resistance and a reliable contact.' },
      notch: { kid: 'This gap makes sure the stick can only go in one way. It even stops you putting old RAM in a new slot!', adult: 'The key notch is at a different position for DDR4 and DDR5, so you physically can’t insert the wrong generation or put a stick in backwards.' },
    },
  },

  dram: {
    name: 'Inside a memory chip', emoji: '🔬', year: 'today', tagline: 'Billions of tiny buckets of electricity',
    note: 'A 16 Gb DDR5 DRAM die: 32 banks in 8 bank groups. Simplified.',
    stats: [['Memory cells', '17 billion'], ['Banks', '32'], ['Rows per bank', '65,536'], ['Refresh', 'every 32 ms']],
    kid: 'Inside each memory chip are about 17 billion tiny “buckets” that hold electricity. A full bucket means 1 and an empty one means 0. But the buckets leak! So the chip has to top them all up about 30 times every second.',
    adult: 'Each bit is a 1T1C cell: one transistor and one capacitor. Cells are arranged in banks of rows × columns. A read “activates” a row, which copies it into sense amplifiers (the row buffer), then reads columns from that buffer. Because capacitors leak, every row has to be refreshed within 32 ms. DDR5 also adds on-die ECC to fix single-bit errors inside the chip.',
    package: { w: 13, d: 13, color: '#16171b', t: 0.6 },
    lid: { x: -6.4, z: -6.4, w: 12.8, d: 12.8, h: 0.8, label: '16Gb DDR5', sub: 'x8 · FBGA-78', color: '#15161a' },
    sources: [[0, 9], [0, -9]],
    dies: [
      { x: -5.2, z: -5.4, w: 10.4, d: 10.8, blocks: [
        ...Array.from({ length: 32 }, (_, i) => {
          const side = i < 16 ? 0 : 1, k = i % 16, col = k % 2, row = Math.floor(k / 2), grp = side * 4 + Math.floor(row / 2);
          return B('bank', `Bank group ${grp + 1}`, side * 6.4 + col * 2, row * 1.35, 2, 1.35, ['#3f8fe8', '#39b58a', '#b064e6', '#e0584f', '#f39a3d', '#59c7d8', '#d97ab5', '#7aa36d'][grp], 'bank');
        }),
        B('cmd', 'Commands', 4, 0, 2.4, 3.6, '#8c96a8', 'logic'),
        B('ecc', 'On-die ECC', 4, 3.6, 2.4, 3.6, '#f2c230', 'logic'),
        B('io', 'Data pins', 4, 7.2, 2.4, 3.6, '#4c5a78', 'io'),
      ] },
    ],
    info: {
      bank: { title: 'Memory banks', kid: 'Each coloured block is a “bank”: a big grid of tiny buckets arranged in rows and columns, like seats in a stadium.', adult: 'Each bank holds 512 Mb as 65,536 rows × 1,024 columns × 8 bits. The chip keeps 32 banks in 8 bank groups, so different banks can be opened at the same time, which hides the delay of opening a row.' },
      cmd: { kid: 'The part that listens to orders: “open row 42!”, “read that!”, “refresh now!”.', adult: 'Command/address decoding, mode registers and the refresh counter. It receives ACTIVATE, READ, WRITE, PRECHARGE and REFRESH commands from the memory controller.' },
      ecc: { kid: 'A spell-checker for memory. If one tiny bucket flips by mistake, it fixes it.', adult: 'DDR5 on-die ECC corrects single-bit errors inside the DRAM, which has become important as cells get smaller. It is separate from “ECC memory” (system-level ECC), which also protects data on the bus.' },
      io: { kid: 'The door where data leaves the chip. 8 bits squeeze through at once, billions of times a second.', adult: 'The x8 data interface. DDR (double data rate) transfers on both clock edges, so at 6000 MT/s each pin moves 6 billion bits per second.' },
    },
  },
};
export const CHIP_ORDER = ['m5', 'desktop', 'gpu', 'dimm', 'dram'];
